spring:
  profiles:
    active: 
    - dev
---
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-config-dev
---
spring:
  profiles: dev #测试环境
  application:
    name: microservicecloud-config-test
# 请保存为UTF-8格式